version: "3.9"
services:
  app:
    container_name: my-app
    build: docker/app
    ports:
      - 8080:8080
    environment:
      - USER=${USER}
    volumes:
      - .:/opt/rust-wasm-snake-game
    tty: true
